### ISSUE TITLE
Quiz Feedback

### ISSUE THREAD

**Issue by udiiin** [yunusbahtiar22/hsi-sandbox-lv3-assigment#1]
Halo Mas @yunusbahtiar22, sori baru cek submissionnya..  

Saya ada beberapa feedback:

## 1.) Layout component

Saya lihat semua page menggunakan component `Layout` component.  
Di `Header` component, button utk memilih "Popular"/"New" itu selalu dirender, dan disembunyikan menggunakan CSS.  
Baiknya disembunyikan menggunakan conditional rendering saja mas..

Jadi di page yg tidak butuh tombol tersebut, tidak perlu adanya element tsb (walaupun sebenarnya elemennya sudah di-hide menggunakan CSS).

## 2.) useState di Header

Penggunaan `const [sort, setSort] = useState("new");` tidak perlu, karena current sort udah tersedia di `useRouter` query.

## 3.) Unused files

API `/hello` bisa dihapus saja karena tidak dipakai, biar tidak membingungkan.

## 4.) Naming component `Card`

Component `Card` namingnya terlalu general, akan menimbulkan pertanyaan, "card" apa?  
*Kecuali kalau component card berada di dalam folder `post` maka bisa dipahami konteksnya apa

.

Barokallaahu fiik...

**Comment by yunusbahtiar22** [comment]
halo mas afif @udiiin, sudah ditindak lanjuti ya mas feedbacknya.

- sort button di component `Header` sudah dirender secara conditional.
- `useState` dalam component `Header` yang tidak diperlukan sudah di buang.
- file yang tidak digunakan (`pages/api/hello.js`)sudah dibuang.
- `Card` component sudah dibuatkan folder masing-masing untuk membedakan setiap `Card`

jazakallah khoiron atas reviewnya.

**Comment by yunomeister22** [comment]
halo mas afif @udiiin, sudah ditindak lanjuti ya mas feedbacknya disini 07a149d2d8f322362a43ce5c4c543fa6b7b76c33, untuk rinciannya sbb:

- sort button di component `Header` sudah dirender secara conditional.
- `useState` dalam component `Header` yang tidak diperlukan sudah di buang.
- file yang tidak digunakan (`pages/api`) sudah dibuang.
- `Card` component sudah dibuatkan folder masing-masing untuk membedakan setiap `Card`

jazakallah khoiron atas reviewnya.

**Comment by afiiif** [comment]
Sipp mas, secara functional udah oke 👍

Kemudian ini minor improvement aja,  
di component `Header` sebenarnya bisa tidak perlu pakai prop `home`.

`<Header home={pathname === "/"} />`  
👉 `<Header />`

Di dalam component `Home` bisa memanfaatkan `useRouter()` utk menampilkan/tidak tombol filter

Jazakalaah

**Comment by udiiin** [comment]
Sipp mas, secara functional udah oke 👍

Kemudian ini minor improvement aja,  
di component `Header` sebenarnya bisa tidak perlu pakai prop `home`.

`<Header home={pathname === "/"} />`  
👉 `<Header />`

Di dalam component `Home` bisa memanfaatkan `useRouter()` utk menampilkan/tidak tombol filter

Barokallaahu fiik

**Comment by yunomeister22** [comment]
Baik mas, sudah diperbaiki di sini e4c51acdf9d2fe6bdca376b67ff6992ebc47a505

**Comment by udiiin** [comment]
Sipp mas 👍  
Dari saya udah oke ✅

Barokallaahu fiik
